env:
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/eslint-recommended
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - "prettier"
rules:
    prettier/prettier:
        - error
    linebreak-style:
        - error
        - unix
