printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: false
quoteProps: 'as-needed'
jsxSingleQuote: false
trailingComma: 'all'
bracketSpacing: true
# arrowParens: 'avoid'
proseWrap: 'preserve'
htmlWhitespaceSensitivity: 'css'
endOfLine: 'lf'
